[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "langchain-community>=0.3.24",
    "langchain>=0.3.25",
    "langchain-google-genai>=2.1.5",
    "streamlit>=1.45.1",
]
